version: "3"
services:
  rabbitmq:
    image: rabbitmq:3
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./Celery/rabbitmq :/Celery/broker
    networks:
      - main_network

  backend:
    build: .
    image: backend
    container_name: 'backend'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: bash -c "uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - main_network

  worker:
    build: .
    image: celery_worker
    container_name: 'worker'
    ports:
      - 80:80
    volumes:
      - ./Celery/worker :/Celery/worker
    command: celery -A tasks worker --loglevel=info
    networks:
      - main_network
    depends_on:
      - rabbitmq

  flower:
    build: .
    image: celery_flower
    container_name: 'flower'
    ports:
      - 5555:5555
    volumes:
      - ./Celery/flower :/Celery/flower
    command: celery -A tasks flower --loglevel=info
    networks:
      - main_network
    depends_on:
      - rabbitmq

networks:
  main_network:
    driver: bridge
